[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
derive_more = "2.1"
enum-map = "2.7"
indexmap = "2.12"
pretty_assertions = "1.4"
smol_str = "0.3"
strum = "0.27"
thiserror = "2"
